import { db } from "./db";
import { equipment, sites } from "@shared/schema";

async function seed() {
  console.log("Seeding database...");
  
  // Create sites first
  const [site1] = await db.insert(sites).values({
    name: "Downtown Build",
    address: "123 Main St",
    city: "Toronto",
    state: "ON",
    zipCode: "M5H 2N2",
    projectManager: "John Smith",
    status: "active",
    startDate: "Jan 1, 2024",
    notes: "Major downtown construction project",
  }).returning();
  
  const [site2] = await db.insert(sites).values({
    name: "Airport Expansion",
    address: "456 Airport Rd",
    city: "Toronto",
    state: "ON",
    zipCode: "M9W 1K4",
    projectManager: "Sarah Chen",
    status: "active",
    startDate: "Mar 15, 2024",
  }).returning();
  
  const [site3] = await db.insert(sites).values({
    name: "Highway 401 Project",
    address: "Highway 401 East",
    city: "Toronto",
    state: "ON",
    projectManager: "Mike Torres",
    status: "active",
    startDate: "Feb 1, 2024",
  }).returning();
  
  // Create equipment
  await db.insert(equipment).values([
    {
      id: "EX-2024-001",
      name: "CAT 320 Excavator",
      type: "Excavator",
      siteId: site1.id,
      location: "Downtown Build",
      maintenance: "G_1",
      err: "G_1",
      hours: 1245,
      serialNumber: "CAT320GC2024001",
      purchaseDate: "Jan 15, 2024",
      operator: "John Smith",
      warrantyStatus: "Active",
      isRental: 0,
      lastReportBy: "John Smith",
      lastReportHours: 1245,
      lastReportDate: "Nov 7, 2025",
      notes: "New machine, running smoothly",
    },
    {
      id: "EX-2023-087",
      name: "Volvo EC220E",
      type: "Excavator",
      siteId: site2.id,
      location: "Airport Expansion",
      maintenance: "Y_2",
      err: "G_1",
      hours: 2890,
      serialNumber: "VLV220E2023087",
      purchaseDate: "Jun 5, 2023",
      warrantyStatus: "Active",
      isRental: 0,
      lastReportBy: "Sarah Chen",
      lastReportHours: 2890,
      lastReportDate: "Nov 6, 2025",
    },
    {
      id: "LP-2023-042",
      name: "Graco LineDriver",
      type: "Line Painter",
      siteId: site3.id,
      location: "Highway 401 Project",
      maintenance: "Y_2",
      err: "Y_2",
      hours: 3890,
      serialNumber: "GLD2023042",
      purchaseDate: "Mar 22, 2023",
      warrantyStatus: "Expired",
      isRental: 0,
      lastReportBy: "Mike Torres",
      lastReportHours: 3890,
      lastReportDate: "Nov 5, 2025",
      notes: "AC unit needs repair, not critical",
    },
    {
      id: "TR-2024-015",
      name: "Ford F-550",
      type: "Truck",
      siteId: null,
      location: "Unassigned",
      maintenance: "R_3",
      err: "R_3",
      hours: 5420,
      serialNumber: "1FDUF5HT8FDA12345",
      purchaseDate: "Feb 10, 2024",
      operator: "Sarah Johnson",
      warrantyStatus: "Active",
      isRental: 0,
      lastReportBy: "Sarah Johnson",
      lastReportHours: 5420,
      lastReportDate: "Nov 4, 2025",
      notes: "Hydraulic hose broke - URGENT",
    },
    {
      id: "TR-2024-022",
      name: "RAM 3500",
      type: "Truck",
      siteId: site1.id,
      location: "Downtown Build",
      maintenance: "G_1",
      err: "G_1",
      hours: 1567,
      serialNumber: "3C63R3HL2FG567890",
      purchaseDate: "Apr 8, 2024",
      operator: "Mike Torres",
      warrantyStatus: "Active",
      isRental: 0,
      lastReportBy: "Mike Torres",
      lastReportHours: 1567,
      lastReportDate: "Nov 7, 2025",
    },
    {
      id: "SK-2023-031",
      name: "Bobcat T770",
      type: "Skid Steer",
      siteId: site1.id,
      location: "Downtown Build",
      maintenance: "G_1",
      err: "G_1",
      hours: 4230,
      serialNumber: "BBT770-2023031",
      purchaseDate: "May 12, 2023",
      warrantyStatus: "Expired",
      isRental: 1,
      lastReportBy: "James Wilson",
      lastReportHours: 4230,
      lastReportDate: "Nov 3, 2025",
    },
    {
      id: "BH-2023-012",
      name: "CAT 420F Backhoe",
      type: "Backhoe",
      siteId: site2.id,
      location: "Airport Expansion",
      maintenance: "R_3",
      err: "G_1",
      hours: 3650,
      serialNumber: "CAT420F2023012",
      purchaseDate: "Aug 15, 2023",
      warrantyStatus: "Active",
      isRental: 0,
      lastReportBy: "Sarah Chen",
      lastReportHours: 3650,
      lastReportDate: "Nov 6, 2025",
    },
    {
      id: "CMP-2024-005",
      name: "Wacker Neuson Roller",
      type: "Compactor",
      siteId: site3.id,
      location: "Highway 401 Project",
      maintenance: "G_1",
      err: "Y_2",
      hours: 890,
      serialNumber: "WNR2024005",
      purchaseDate: "Jul 20, 2024",
      warrantyStatus: "Active",
      isRental: 1,
      lastReportBy: "Mike Torres",
      lastReportHours: 890,
      lastReportDate: "Nov 7, 2025",
      notes: "Minor vibration issue, monitoring",
    },
  ]);
  
  console.log("Database seeded successfully!");
  process.exit(0);
}

seed().catch((error) => {
  console.error("Error seeding database:", error);
  process.exit(1);
});
